apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gizmosql
  name: gizmosql
spec:
  ports:
  - port: 31337
    protocol: TCP
    targetPort: https
  selector:
    app: gizmosql
  type: NodePort
status:
  loadBalancer: {}
