apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minio
    spec:
      containers:
      - command:
        - minio
        - server 
        - /data 
        - --console-address 
        - ":9001"
        image: quay.io/minio/minio
        name: minio
        resources: {}
status: {}
