apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: default
  labels:
    app: minio
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
      nodePort: 32295  # choose a free port
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 32296
